~# Use lightweight Java image
FROM openjdk:21-jdk-slim

# Create working directory
WORKDIR /app

# Copy jar file into container
COPY target/*.jar app.jar

# Expose application port
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
