pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        DOCKER_IMAGE = "sreechandanareddy/majorproj:1.0"
    }

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/sreechandanareddy1318/majorproj.git'
            }
        }

        stage('Build - Maven') {
            steps {
                sh 'mvn clean package'
            }
        }
      }
    }


